"""Add AI suggestion fields and processed_emails table

Revision ID: 88d89c372a36
Revises: 8be9e5cb0fc5
Create Date: 2026-07-15 17:59:18.275203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d89c372a36'
down_revision = '8be9e5cb0fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gmail_message_id', name='uq_processed_emails_user_message')
    )
    with op.batch_alter_table('processed_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_emails_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_emails_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_suggested_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_suggestion_source_email_id', sa.String(length=255), nullable=True))
        # server_default backfills existing rows in the same statement --
        # without it, Postgres rejects a NOT NULL column add on a non-empty
        # table (the model's Python-side default=False only applies to new
        # rows the ORM inserts afterward, not rows that already exist).
        batch_op.add_column(sa.Column('ai_suggestion_seen', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('ai_suggestion_created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('ai_suggestion_created_at')
        batch_op.drop_column('ai_suggestion_seen')
        batch_op.drop_column('ai_suggestion_source_email_id')
        batch_op.drop_column('ai_suggested_status')

    with op.batch_alter_table('processed_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_emails_user_id'))
        batch_op.drop_index(batch_op.f('ix_processed_emails_application_id'))

    op.drop_table('processed_emails')
    # ### end Alembic commands ###
