"""Add gmail oauth columns to user

Revision ID: 8be9e5cb0fc5
Revises: e3a267bffed2
Create Date: 2026-07-15 17:53:01.977162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be9e5cb0fc5'
down_revision = 'e3a267bffed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gmail_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gmail_connected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_email_scan_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_email_scan_at')
        batch_op.drop_column('gmail_connected_at')
        batch_op.drop_column('gmail_refresh_token')

    # ### end Alembic commands ###
