"""Add AISummary table

Revision ID: e3a267bffed2
Revises: 8f78a737d7b3
Create Date: 2026-07-15 14:33:46.031885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a267bffed2'
down_revision = '8f78a737d7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('flags_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_summaries_url'), ['url'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_summaries_url'))

    op.drop_table('ai_summaries')
    # ### end Alembic commands ###
